# Generated by Django 4.0.6 on 2022-08-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='media/default.png', upload_to=''),
        ),
    ]
