# Generated by Django 4.0.6 on 2022-08-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='media/default.png', upload_to='profile'),
        ),
    ]
